### ISSUE TITLE
Incorrect port in README.md

### ISSUE THREAD

**Issue by shirishp** [docker-ninja/go-app#3]
The [README.md](https://github.com/docker-ninja/go-app/blob/master/README.md) says to `open browser and hit localhost:4000 ,you should see hello message` after running `go run main.go`.

However, by default, the server seems to start on port `8080`. Can we update the README.md with the correct port?

**Comment by thamaraiselvam** [comment]
Fixed https://github.com/docker-ninja/go-app/commit/2a6d0640a8b4ac000477f8e868cb755db71b29ef
